<?php
/**
 * SclZfGenericMapper (https://github.com/SCLInternet/SclZfGenericMapper)
 *
 * @link https://github.com/SCLInternet/SclZfGenericMapper for the canonical source repository
 * @license http://opensource.org/licenses/MIT The MIT License (MIT)
 */

namespace SclZfGenericMapper\Exception;

/**
 * Interface to identify exceptions generated by this module.
 *
 * @author Tom Oram <tom@scl.co.uk>
 */
interface ExceptionInterface
{
}
